### ISSUE TITLE
How to render locally on my mac's clone of the git?

### ISSUE THREAD

**Issue by mspritch** [CLIVAR-DataScience/CLIVAR-DataScience.github.io#1]
I followed the directions about how to install jekyll on my local mac using homebrew to get ruby3.0.0 before using gem to install jekyll. 

Where relative to the contents of this repo are we meant to run "jekyll-serve"? I am able to run it from within the _posts/ directory including when I create a new markdown and am able to observe a local "_site/" folder materialize with a html rendering of the markdown code, though it is generically formatted and does not look nice like the example you committed to this git nor does it contain an upper level .html file to navigate the various blog entries. So I suspect I am not rendering correctly. For what it's worth I also see the following warning message when I do it this way.

     Build Warning: Layout 'post' requested in 2020-12-14-welcome-to-jekyll.markdown does not exist.

Alternately, trying to execute the "jekyll-serve" command from the top level path of a clone of this git gives me the following error message:

pritch@mikes-mbp US-CLIVAR-DataScience.github.io % jekyll serve       
Resolving dependencies...
/Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find concurrent-ruby-1.1.7 in any of the sources (Bundler::GemNotFound)
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:175:in `specs'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:245:in `specs_for'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/runtime.rb:20:in `setup'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler.rb:148:in `setup'
	from /Users/pritch/.gem/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Users/pritch/.gem/ruby/3.0.0/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	from /Users/pritch/.gem/ruby/3.0.0/bin/jekyll:23:in `load'
	from /Users/pritch/.gem/ruby/3.0.0/bin/jekyll:23:in `<main>'

**Comment by nbren12** [comment]
I haven't actually run it locally, but I'll try to debug it.

**Comment by nbren12** [comment]
Running `jekyll` serve from the repository root works for me. Can you run these commands and paste the output here:

```
jekyll --version
gem --version
ruby --version
```

This is the output I get:
```
jekyll 4.2.0
3.0.3
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by mspritch** [comment]
Thanks for looking into this! Looks like my local brew —> ruby installation of Jekyll itself might not have worked as I’d hope given that the answer is:

pritch@mikes-mbp US-CLIVAR-DataScience.github.io % jekyll --version
Resolving dependencies...
/Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find concurrent-ruby-1.1.7 in any of the sources (Bundler::GemNotFound)
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:175:in `specs'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:245:in `specs_for'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler/runtime.rb:20:in `setup'
	from /Users/pritch/.gem/ruby/3.0.0/gems/bundler-2.2.7/lib/bundler.rb:148:in `setup'
	from /Users/pritch/.gem/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Users/pritch/.gem/ruby/3.0.0/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	from /Users/pritch/.gem/ruby/3.0.0/bin/jekyll:23:in `load'
	from /Users/pritch/.gem/ruby/3.0.0/bin/jekyll:23:in `<main>'
pritch@mikes-mbp US-CLIVAR-DataScience.github.io % gem --version
3.2.3
pritch@mikes-mbp US-CLIVAR-DataScience.github.io % ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**Comment by nbren12** [comment]
Hmm. I'd try to install the same version as I have above, or as close as possible. Maybe `rm -rf ~/.gem` and try installing jekyll again?

```
brew install ruby@2.6
gem install --version 4.2.0 jekyll
```

I don't think I am using homebrew to install ruby. I think I'm using the`gem` bundled with mac.
